version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-bmp-bot
    environment:
      POSTGRES_DB: "prod_db"
      POSTGRES_USER: "prod_user"
      POSTGRES_PASSWORD: "prod_pass"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres: